version: '3.8'
services:
  db:
    image: mysql:8.0
    restart: always
    command: --wait_timeout=28800 --interactive_timeout=28800
    environment:
      MYSQL_DATABASE: treningsglad
      MYSQL_PASSWORD: Urstammer246
      MYSQL_ROOT_PASSWORD: Urstammer246
    ports:
      - '3308:3306'
    volumes:
      - db_data:/var/lib/mysql
      - ./scripts/table.sql:/docker-entrypoint-initdb.d/table.sql:ro

volumes:
  db_data:
