version: '3.8'
services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword123
      MYSQL_DATABASE: TreningsGlede
      MYSQL_USER: treningsuser
      MYSQL_PASSWORD: userpassword123
    ports:
      - '3306:3306'
    volumes:
      - db_data:/var/lib/mysql
      - ./scripts/table.sql:/docker-entrypoint-initdb.d/table.sql:ro

volumes:
  db_data:
