version: '3.8'

services:
  mysql:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: adiam
      MYSQL_DATABASE: trening
      MYSQL_USER: root
      MYSQL_PASSWORD: adiam
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3307:3307"
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
